apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.17.0
        args:
        - --source=ingress
        - --source=service
        - --provider=pihole
        - --pihole-server=http://pihole-headless.pihole.svc.cluster.local
        - --pihole-password=$(EXTERNAL_DNS_PIHOLE_PASSWORD)
        - --pihole-tls-skip-verify
        - --pihole-api-version=6
        - --domain-filter=local
        - --domain-filter=lan.tapslab.com
        - --log-format=json
        - --log-level=info
        - --interval=30s
        - --policy=upsert-only
        env:
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-password
              key: EXTERNAL_DNS_PIHOLE_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
