apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
type: Opaque
data:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:l+RXZs1C7Uckg35dEWexfg==,iv:CzUyB3fRG80w0e4rVHw0oRbTds4WnAGDlkklk24thuY=,tag:tsqeA325rlhu2Breo+IDWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwl5ersszyeyx6hp53w72j4zhw3ucy8t37czcl2y9zlfcrjdqy5qs8cvxd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVFF0d3Z0MVJXT3o3MEUx
            Y3M2NlF6cjlBWHdUTHRoeGc3d2Z1bkRqQlhRCkptMzRaN3U5b2pDam5Dd1J2enBs
            U3pkbFhuTkV1UnlXTnphRjdLekUvU1EKLS0tIGhWVi9JLzF6ejcvWkRCRWJ2OUc2
            UkxqR0s1cEtHUzFaZlEyaS80ZnpIelkKQcmrmARXpEcHFadFi45kvM37BlpQsMeX
            zAgaCBky2Ip0/hyBD9KE4lJyEgDW62hBrF7MQtG0BC3B4WK0UVGxwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T09:56:25Z"
    mac: ENC[AES256_GCM,data:+Aso+aFkF9MYbLLktCkbguC/XyC4YZVLaqTUtaS7AWH7oxIDEXhNMLJZEJl4wgwKz8pl0Fpf6ZjIOSDLQ9exIvXq6seCwUGpI9NjwSfck9uVF78ATlT7eeuGTO/6+1ONPbVSr0HtbtYkwDVhVf8bSnpOZJcN9l/RnNj1vHZuel8=,iv:37m/V6qVacxlCdv2TTALTNgPSIQX6Yxl/8h7Y4BHa34=,tag:078rE3Jfm9VJ28ARZMMoOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1