apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: template
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:qwYLKAa4d839VIlEXexlG7rVVPd8tq3JxarQZWkGymnBRA654Evi9w==,iv:raZXoKcxpIBtpWo29lDkyPFekA3iCLq0KA9cNbGDAdE=,tag:uzBK7/1XzCC7yRjEFSAZ7Q==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeHlDQVZjNGs4aGpSZllu
            TFJHNG9yTklLTlFqS2lmb3dZcGZzU2JYa2w4CmpuQmtkUTVPV09IK29SOHZzdisr
            VHlkcDBlS1A2d0UwR1dOcnlZWSs1SGMKLS0tIDZrZCs3QS9LSmEwMytEY3NWUkxu
            b1g3RXROU1F6VHhnY0pGOHZ2bkNLTG8K+hHWmGQQ1zAbsH3FecZqNbFQyx5BuW2F
            bbM6kT8zjdofut/GNrey5AwxZ2/6Ueahx1dl38ioRbqPbIJ0XtBUnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T05:43:23Z"
    mac: ENC[AES256_GCM,data:rmldbPl9e2ZCD3qd/+77z7egPlFjiShd1LNjW17v5nYRZ2YLlIJo6C3419l28n/9uQpYjhJjObfO5ZThsbuUIzJAfzJWn4zKBsIVNQ0W+RVIHFbWcYkU9qZEfYV/03N89DHTPwpWLKHiU/4XlyGTTd6tM94SROlVsGjLUrNDMwI=,iv:95BxpLumYNzGHaVmET7uFAnsDYmds0dbJBRw5s1rnPg=,tag:MVgD1ws0pkRvEMkaSYL+jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
