apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: template
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:3rEY7P3ODtlRf4I6km1hhdPqz3diThizQZP9gh6t5a/tqXd0TvuAklHgyn0jrASsNRkAKbH7JEZeFjm7mH6fFbMMa1vqbGQJDYNCfpNVQ6+fJsDrR4NVsSWrpyZkyOsne+JQwNmGMAPBDSwKXiGjTaopoP9rne3e+1jlw2H/5bxJFBJRvQ==,iv:hRbfvtAUpVgdPVzVKiG6J8uUgTwHhOGgZUDHr3DoUHU=,tag:7f7APkoT5tKd3XTqNqSBEg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZjhTWkhLZDZBNTdNb2pS
            VUZvMVZPNnlPVllGRlozR280a2VPZTNiQ0RBCjMwd3ZOWDk5UUs2S0FGdnYzUzdt
            cTNtL2phU2lqK3RtQ09LbS94UmFuUWMKLS0tIFpDQ0NrZWpPYitqTHEvSXQrYUdD
            QTQrWm9pd244aXBob2liRUhybHdLYnMKfZ8g9xV8V/pJxGRyBsU+WW3yAd8+03En
            EdfFvBl/2lnqo+yrVqOizVAuf1xcxw1QiW+a+IKKhRsSrm38zNR9iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T05:43:23Z"
    mac: ENC[AES256_GCM,data:mvsmpwNvQH0jY3sxvSJ7iEwQTnMkS0VaT+f2EssAUdiwHgUX7hMcfSAIsZzb865PrICgc9SZZMq34ecMllUPHFokn5vEIOiObckDssczGjy+FMjQ3mJ6/1YcoPeWX9xU/Luah5Imu1h4Bi79ZTv5FObGFNeMYXaPRf71bFxUWM0=,iv:l8xMMfko7ZbVREr5OPt8eQEOJehZuxZ5l1mgfVX75gU=,tag:qtufdC1xwUKIkkiqhERFMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
