apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanostatus-data-pvc
  namespace: nanostatus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-retain
