apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:34sEOnFSioJpoxENlf2tSDdW/eSdr4cP4w8RIkIPZaFS0APdVaiwFA==,iv:JdMREb0IZvZS5TR0ieAnksUCep4Iz9yjacqDJFYo5zE=,tag:BD1kP1ae/m6UcuA5O03Xtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYVF5S0E5eVR2cElXb3Yz
            Z0M1YmMyczlBMkNuRGU5dHpES2NocWJJejM0CkNoZDc2UTZkWEEyTTRxTkVzRURx
            S0NIbmVvTGJ4eEV6YnQrTTZiQ2RLZ3MKLS0tIFpTZUJGM2hDRWswRFluVjNaTzZv
            Tk90TzZwOEd0cVRiSHBreGpqWFY5WGcKajMhN4UxEhZRzCBKaAWXonfAjlG2zQ1r
            6onZwcrguwlzF9H3knqS7DEfy6YF22ga2DELbctiULJZa4IiqCE2kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T04:17:44Z"
    mac: ENC[AES256_GCM,data:6LhocbYVsORsva1FbsNuiOTJX0ioO5xB087haKTrdjufzGukV2gzYjHowRI/TBIbHHi/k/3L8REMvq1jMWoW6XhuKuc3kTXTLQkTy+bIoqT+JB9z2NFEvj4OrIzN2NTK9ElYCgYAxGHqx/Ruq2wDPsGq2qrtL9kBp8U3hZUIP3Y=,iv:2VWAxSWtSOpDe8ic5PRTiSTKrZXfGuL6hB0+5UqCEp4=,tag:qT32zjgX5WhKkqfzy8+LTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
