apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: gpu-operator
      interval: 12h
  values:
    operator:
      defaultRuntime: containerd
    driver:
      enabled: true
    toolkit:
      enabled: true
    devicePlugin:
      enabled: true
    dcgmExporter:
      enabled: false
    migManager:
      enabled: false
    nodeStatusExporter:
      enabled: false
    gfd:
      enabled: true
