apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: n8n
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:vu0xULQOKpuWY809vakazWxPVXrtsM5A/gFMJUxCKY+JLIxpzPbHww==,iv:fyy/LurjvqpvR0jtNo4JmIoEhxw83+feKualMJojcxI=,tag:5v7BN0Bgzh5w7xZ4QT0D9A==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M2NKSEI1NXp2cFhFRVBk
            cGlOM2lReGFDUllzWjhUZHczTFVHVnIzSVJFCmNtdzBVbFNlS1U0WHpJNzZqWUNQ
            Wkg2REpKM3g1b3grZWs3RWJodm1oeGsKLS0tIEkwRXpGYVFpMmRtVTJ1NXltVzJq
            bUpqR0lteExOUXlQcEh2bjBxaHA5UGsKrEZwPYxXTbIcgEP6wShG6ss8BRBSIL8A
            dt9+p8ehlaMq26OAJPIx1e+tukhVNjOpX7lV49y7KxpYQqJvbkXgpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T02:38:28Z"
    mac: ENC[AES256_GCM,data:Xa7iiEVh3SfBiRvJdSrEnzKgSUoYkmqiaHxurr1jo8io17ecaWqC30m66fc7oyom1DKdTgwhbdw7yckQX+rq0jZkdLKX4uIUqVpuOme5Sv2lrwaIRx6JV/e26md482RvBuCW0opbxac9EY+bdE4TeXvfmkHN8EO9bCS3cEORY5k=,iv:G3jrvSCP6yPptcj3ahAXhOqwZAwkQ9wx9jB0Fshk/d4=,tag:xDJJqhiF8XGj/gOJ4ekD4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
