apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-credentials
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:B+Jn2t2Vy+/MMkE1llOw4xjuA+0+mrXXpAGYMCmPYvs=,iv:0i01OzIVyGApGUsjvRB/KYUSH/SJqVaKG8n88OSkS48=,tag:J3H/P22gEoPdCa3eIpwM/g==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:DZEVy/kZF2HFQDi8Or+MjkoEVTcRJ0vaXECnwlBbbthINufNRuLI7M7gZwnl0kuERZiYF2qS9Tfi4A3AF0pCdQ==,iv:wfAW4tJyfm2ZxZPY0Lo3SZzWtfQ7ZnL3LWMD/q/4fqQ=,tag:p2HQdTHHdyawFUI2XzkkdQ==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQk51d1BuQ3Rhd00vUTJ3
            RUptOFFDU0I3enlUdzZ2M0h1T0NtOTdFL0dnCkQ2OUh3TkoyOFVuNWk5RGRxekwx
            NkNEdHkrRk5SRE1oVmVoOVlHRmlralEKLS0tIGpvZTF4V2UyMDRDc0dBRnpNWm5w
            RmFJUDFKVzYwWVNpQ3VKdzZuMVB4WmsKUGvofZdetIEIgPbCxDQkFjSwZ0+bQr/a
            EDR/sKBdFYB53gqBUiAHswB9fvUJGiHmPGzEnJ2uH2Shq0uhWoGRcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T04:43:06Z"
    mac: ENC[AES256_GCM,data:VJo3T4QeBGwvYoPccqPeOW/uCr9BQrsx2J9c8gKoQ5+mh/HV6SqdIykr+mFBScZ2afmBZDHBDI8LjRPIEV415mhkbzfS7MwiLk5lo6yFsaPhr/Z0NQlAxGAC8ZgB2nssffZErsh7GhkdGskHuXXisIvjMdgMTghLv6Qmn+ziB8o=,iv:eOygERgnhSiXrOPf9cWI5l1GvmcwlTY6Vlyi4KRtCKY=,tag:SbuqCC661X8i29gTj00Guw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
