apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: n8n-binding
  namespace: n8n
tunnelRef:
  kind: Tunnel
  name: n8n-tunnel
subjects:
  - kind: Service
    name: n8n
    spec:
      fqdn: n8n.tapslab.com
      path: /
      protocol: http
