apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: angelorooms-data-pvc
  namespace: angelorooms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-retain
