apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubernetes-api-lb
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/tpural/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubernetes-api-lb
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kubernetes-api-lb
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-api-lb
  timeout: 2m
