apiVersion: v1
kind: Secret
metadata:
    name: family-tracker-app
    namespace: family-tracker
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UMVZ2T7Eted+t5wPgeFsMsChc6yKCRZE25X94UNPfHGS2YFBEsHl9oYyZ9D4UBgJatSzqpKIsn9UFBMvTaO6/ZdOuPuw0gZOB+h0E/c97VS6dBlDzniTMjdx,iv:4SyeggB22Bjbv1ZxIgq8aypGQ+bzqzW2WsPa9fd/ItQ=,tag:pnu+ITwrp77Y+X55Xftfnw==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:g4sLfkyJuQvyNZs4XvA9RF4QUd9AhvoWXjl0ufQ/jkp1Ei5/j5q/5B3J1nA=,iv:fZFLGpg2+m2GxxuaCaFVAVmLh91RL8VgR84KSyVJrjs=,tag:YqBHS3uiAPABIRjXAJ8MtQ==,type:str]
    AUTH_GOOGLE_ID: ENC[AES256_GCM,data:wz369uv8dbnUxwBedst6SX3KxmCbzyKjBDjktn1Iu3C9+gkzLdkoqkuBYY3A2+oHMd5+WSWA92i40CqPKkcwJk4gixWzy30z,iv:PGhKplFHFJlytakfJQNntfZEuE+3sQUGT0sAPlgI+0s=,tag:1bywyTnwEWz7zmLCGji5NQ==,type:str]
    AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:rrbHIOoYmkjX/vSiRKbcylIR9Ixnrjdd/5iFeovRNtMSDD8=,iv:uvp2isyD87WyehwZccxJugh1ciLVfJhRbtTXdHumEFk=,tag:x3eE2ll19Rn90OnOa99Flw==,type:str]
    ALLOWED_EMAILS: ENC[AES256_GCM,data:axmH8E4XkIug/T4pp0xO7rhLdusOHVnD2ytHPiW3xSpGimqBeKPdGhw=,iv:ZWIiCuaURGytlO88Bg5KR8xDD1aN9gngHLnrXeOr06I=,tag:QJmcZoVyjGVXXuGK9Cmbzg==,type:str]
    CRON_SECRET: ENC[AES256_GCM,data:tE0kw2YPpYcaztnhB55P/E6Cg7U2TH4fRkzdWoo2TEDCjigSFbo/rw==,iv:MrjGoYXPlCjRDgvN1O/BbN80UUycfUpwOzZals3oFz8=,tag:hC1dIEgG/3OS31mSfaj6BQ==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTW8rdkpVY3hyTUJPNlNX
            aFBxRGJQMUtBYzNwVjdjbTNta3JobW8yb2dzCjc1dDdoWG5GOWxTcGhqTHNkWWZG
            a2Fjd2Evd1hhczExWkxKZHBqNmNaZVEKLS0tIGVyZGpZYUxOTXF0S1NuL2hrVGd3
            VUlSR1hyaFJrUXMyWUdWWVBsSDdOT2MKlZkOyysm9PJTidGI9KHhRzG17W9AoTH8
            QeVTExZZcXgsVipyTWzbp9q7d+/CP82xB8Yve7NaLqX0kzt8mFDchg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:56:29Z"
    mac: ENC[AES256_GCM,data:2G9X8CQipXn6hEYd93jvsQN51l5pP3nZuoX3oAmdEcS4AuNi2oDefouRzAOIE1lL8lUDz0L/Py5NL/liMvJT+LX0W2oHW5JoNyAXSlNlRK3y+GE+Q94xvko0XKSetZla4Lc517K3PmyxMFKTaIizkshrICaoN0n06GyUd2oRMB4=,iv:TH36p0rGrmJSnHnaod6p+n6gQRxhQdOzfzpbEt4IFtw=,tag:ybqZeGWAbNnfj54f4CdYPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
