apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: family-tracker
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:CUYdd9yufQUiGrW2BN+G6WYd1ouJuIwkM0/3oCMINwwSgrPYGOEgeA==,iv:CUoJYpiVg1EjUKU9f7A0Rvmeo2QpDLBzXLy0ApgL6oU=,tag:1O98p0aIuAy0aldVbbBFfA==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeEVQaGJwelkyNnVYSFFa
            Nk1kMjlHbHpPY3RNM2hnVFpTRE9ydlJLbkdVCkRTZ0NOdXhaWWtpemdlRnFpOVBp
            aXpjeHc0ZEVHcnNqOXFDN3EvK1dWTGcKLS0tIDlFWkVFODBmT0RuMWZESnNobVgw
            dU5zdGs3K0lRMWk5RWpLTFdZSkxtam8KbGKwyCutI53YmGsKGf0owRVqzezBeBPX
            AF5feH+eetaaVo4bfdA7vGwrFq3gqclIfaLNIdyo0Iszol4B/72X2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:58:06Z"
    mac: ENC[AES256_GCM,data:+1NFDJ+S1noj65aJn5gFjEZ7R29KqUZtHZSb2jgz40ivnewXE12THiMmhMadDWTso3RG0nw1RrYPEGZJ43agM4zGJMvzOQAEzMKCyGp2sXaovYeS+VRjG2YvmxK2yegfzWTnZPeYvEggKez2A3Ijd9X01TfrMLUb/KsPdU/arzY=,iv:y+aR9hzTNOOxdoGIXMJ7wpBB258Zc0LVnyNOK7uV/PY=,tag:EPPeSvkJKb5nSVkHmiC19A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
