apiVersion: v1
kind: Secret
metadata:
    name: family-tracker-db
    namespace: family-tracker
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XPhaWRBvlVLoYNjydQaxFNve7SrIRjdM5EbHaH+HcFw=,iv:okkn1E1qVrlQZ40QJHhNi0+Ujb4k1r8JbHpxe549TOg=,tag:vgV8A+fz1c+FYQlhuc51Jg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjJKNDR0TnB2ekdBaGV0
            Y1Bua0dSTEZKYnVLTUFGTytwc1poNTZZOTBzClpLQWVjRlphYjExVU1BbDh5NXNP
            MjlZQTN5SHlCYkhNYVlFU0x2akgxS0UKLS0tIENhdGhtaUs2UlAwbUQwRURSN00z
            TmtERVlvR0EvM1pWQUtZYW9SSnRNaWcKy0zbfPbNGBIOLkNIWcjTnbKNH2bBgAMn
            kb9xFVn4O+m+nCyswwQB9L8OcyMtek9ag3GEsoxPZJOqaUuk7aGsSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:56:29Z"
    mac: ENC[AES256_GCM,data:ZVtFSGmudiBOwv/vQxrQe3RzL8FdRbzv5/49udm2mZs0a3sNpTHjQqs2/MRf3Ed9jAiS9oGk28xvdTH2YYDzzDOD7tZUcEyiPqGAiCVeGnC6kcOFa4ONHLl7ge0XuP6SMEy4X82z2qrCIyb46lvNkvn5+bakI+4SyguzN7Oziuk=,iv:ioEQxYq4xNIRYCs2JS91uTFlTlozxbcXkQ1amH+GrrQ=,tag:XiygdRFN8jgyigVFlBm+5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
