apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: family-tracker
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:eyLciay4VZ7147lmps/Mt84HzgHfIcKdlCGI7lJHxHdCx69dlBUkstU8cFXx3p+lPKJFA3C4Y+KF0BXX8AVacc6bNIu9KDVjl6awYC50188BfJmdqY2MPvnLkYkc2zjd3KDh5invc4nloN0G81nvQ4bRqC+uD9xuPX6O2jo+1GuqSHTO7A==,iv:xh6DlbEYxt/qiGH6MQ0SLS9EY4sEJ4dJMB2GNCDYsW8=,tag:sHTbXo2fbdKU5HZGnZ/GSg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ1RpWkgyeEE1Qmk3UGJH
            VVZPMHYvMzFWeGlqTWJEUktYeFVJY2xXcmxBCll4Z2I5eDZNQ3cvNTVsSjZTUFRp
            VUc1K2NBVWQwNDZQYUw5K3VoNGtiYWsKLS0tIEpFbGFZYXloOXJqNlMwbzJTRkhF
            MGJmQnA3RVRpYWVaaDhiSFY2NzB0QmsKNgO7gmEnk3o16gh3IBD/JBWz+cO+OR5G
            YeE6SIteLlVhQgvDv7SzyDNU5Ld/5HOHLQsz0diUBNiJIkYaegp+0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:58:06Z"
    mac: ENC[AES256_GCM,data:WPj3PR/DxDpk94YzLSsPJChC1fxvZ+jei6PaNEE0Lp10vk9IfO1w9hzprt/W2VV4nr3vCdcrcHer3f67zbvzuBXgtLMrd3qGsDxTwBevduQ9YXT96Kt3vPJfFSxcB8iyHUKdxaGePP2PUKQgPP1XjdMz67JKpZC4/iNonslMLp4=,iv:SCKzEaOXaPskgdpeXIIdw8zTbuIse+Bq+9w8QyguFxU=,tag:jLl8oLTLaYCx8mYP8HXFbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
