apiVersion: v1
kind: Secret
metadata:
    name: family-tracker-notify
    namespace: family-tracker
type: Opaque
stringData:
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:PjVYduuhzdRvyBpI64Ugh2Jp8iU2pebO+47WZ5vNO7ewUNCMoPTFjWuqXyVvmsFuGNfxNHwS4J+qamBk1IQmhR0qplrwvZW8IHdUPvS+RHWvyRu57mov,iv:p6ulrY0Vl2YTYTk/tLfuHG9xbs+B84W4E+UeEm5ECh8=,tag:3dSBS4dsxgAK+XTIwv6OUw==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:CGM4SJG9+yu09yhTO62v0v3BzHtWEarHVTeGGd1tCea7+oyNkr686IbsOA==,iv:22oXL/4ik8ucezmpEUVNwtf6NuZAOS3FrLzrE4rQSMs=,tag:HPUnLad0mVbk0w9brBHGQw==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:egdQVkPRoFdExQdOGOc0FhKHzLQtUN1do6AQzkc=,iv:6dldThf3gzTl2FNaqsAgbXyDZveS/LSiQC4j3E89UD8=,tag:/fEKUSv/F5DkDs7HSGviag==,type:str]
    #ENC[AES256_GCM,data:2X4RJvwmpJEx+e/dEvYKgq3oCo24cjsh4x76pCdTKTY5GX4G47kJULAR+CeX7TZQwxSsobyFqzfCYRCK0JF+90GuReY03cYL/rla4g==,iv:r7vj8p7C7yWYqdlUY+NafNuyAIFHEM0bu9892o6TbTo=,tag:YPZAx0nxVNjrOVrQJkUxPg==,type:comment]
    #ENC[AES256_GCM,data:H9eebCjrw0SIi/p61H3Tygq40bcjefTsjYCN9JVh,iv:cQ68lcAsB0jbJuQXls7RCzQloOIxORGvUKMjxTDpZw8=,tag:3jVcbJA7FQ7mb3PgF/IAhw==,type:comment]
    RESEND_API_KEY: ""
    EMAIL_FROM: ENC[AES256_GCM,data:e4AK1hkilR7/WmCU/WSJubzD,iv:OVYOUgOSrxzkb6xRAsGh5bcfKBLxnDzMZWlCHmSqMng=,tag:v8V6KJjJLRZ0ACIjwVoApg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUytrQS81eXFMd0dEQ0pa
            SksyaE80MGtNcmJjNWdORHR2K3lrcmlQMW1rCm84dXJxNmxnc3RFTlhqMml3RzNX
            eVZKdEVWbVM5cEZwMnF3SWlsb29XTkkKLS0tIC9namc3dmVEVFhoLzVJTSswbVdl
            aE8xTFJBWnpOQ2NyT3lWeDI5NlJTUGcKljDtfVr9FuxwNZlPFWCUwATjiYzUkp+y
            ImH4mY/PqpdB4GMhtliZ//hHHu1QmIwnUwckNxmRWH46HVT95+zHSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T06:17:24Z"
    mac: ENC[AES256_GCM,data:OFuzvWLqUQ1VRT2ZqND0iPdbRdtw8WbnUDcLohiUZR6W9+etn5KE1Wvu22Wg69XpzReFK9RpwhHrHc61JiWYIQdCp0bM98aW/oemkTiSl6B71MZrp6K5XIllbHhFFCB9NhbX348GNuAIpCajGG9YZJjqEmYYAdTPtT1c/VA2DfQ=,iv:zZe3+5o0vtexaUFEns2G/guV/DM/vBRM3TjDGhGfOFU=,tag:eoTulvP1vnqwuhHL/bVV6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
