apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: duty-cycle
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:ePFjVp00WtJntZaCzvcHTftWmsGfX2ckEokl7rakiXe581gC1MwKhQ==,iv:7gL6OpQNnXn59OSSEeLMJgZ8Svn3CO3HTzND6DJBoi4=,tag:7b37nunOKBaG1CxTRsTYjg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ0hLQVFPR0YvV25pd1RY
            ZzZZazhVcDZiK1k4YktLbGtTcVdmQVRmVW5vCnZjNHJtMzdsOS8rYUt2UWRwdlRT
            MTkwYW55bmYwRkZyaVdMRGxOeWF4QlEKLS0tIFpFWGtPRkNLLzBzRmFCWVpHcGdm
            MmVqS2Z1TTArOXk1RWlCMDhHbks4Z2MK3+GAk+bHnZUvkdz0oECpWO137+skAhyE
            eyAHgqLA16G8TDbcdb9qS2BPUJ+C26R4zbNb0keh4dHX/7+th2Mzcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T05:36:47Z"
    mac: ENC[AES256_GCM,data:v8Dc+xmTEqEXCWHzbRoFvkMnF7RHDivD/70S7JakovJ/vldBiQUedZE+OGl04C1pUlnZXgD7KsQopZSDKIA84gfMleRrCQNWVooSw4AeKpIZUg58JYoxaGY4JUee4ctvOdWpAZ0O5DcOzrCQe3ISDE/Sypn3s3tbw6E96pnTwp0=,iv:wwMYtL1Ri3LS+9jdhHoPPra3L++JLGmL+Ng/ikhq0QI=,tag:nsk4ZMHyZ2iV3TwCIYgAJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
