apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/nfs-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system