apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
data:
  conf.yml: |
    pageInfo:
      title: Tapslab
    sections:
      - name: External Sites
        icon: ':globe_with_meridians:'
        items:
          - title: GitHub
            description: Dashy source code and docs
            icon: si-github
            url: https://github.com/tpural/
          - title: UniFi
            description: View open issues, or raise a new one
            icon: si-ubiquiti
            url: https://unifi.ui.com/
      - name: Local Services
        icon: ':house:'
        items:
          - title: MikroTik Router
            icon: si-mikrotik
            url: http://router.tapslab.com/
          - title: Pi-hole
            icon: si-pihole
            url: http://pihole.tapslab.com/admin/login.php
          - title: Synology Nas
            icon: si-synology
            url: http://tapsnas.tapslab.com
          - title: httpbin
            icon: 'fas h'
            url: http://httpbin.tapslab.com