apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/public/conf.yml
          subPath: conf.yml
      volumes:
      - name: config-volume
        configMap:
          name: dashy-config