apiVersion: v1
kind: Secret
metadata:
    name: wil-auth-secret
    namespace: wil
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:1AcDYhgOYYBaLVeWePBA42ihMoTk7Oxf5Rc4y23I0lxG+8EvPQcikzRv7AFMAuD5BUyzag/ME4FTXZZFfL+PAg==,iv:m3nlSiOT3fu7pYLCwN1KuFAax6mMm84kIQS2NH40PnI=,tag:K4y0wiONjaffS6lDgLfwmw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0xPMc2fG0orh4w0M9j9roddtV1VdvjcVi+Kv+oFiyw==,iv:CUKdHbin3SG26n4lCBsff2sNmJF4xDnpse5fh0jVpNY=,tag:il0z1irXYBDpUZpcKjvefQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:GO9HTUEXq0q48TOD43TlcDS4HbyDvQ==,iv:gtHcnHIhABbVfz2r91NV7d8vueJlR0ZdYjZGcVaux6k=,tag:Iiv9jni06u7ZFIO/OIYWag==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:EOLVqlmWVDAavnjBDXz37ufNP2L8PA==,iv:DNfbaJm2yAp1oUyqSRkTSMrMFmJ8M5TcWjMVVeMxjkw=,tag:KR4w3Qwr0o3HwZ1xnmRpZQ==,type:str]
    allowed_emails: ENC[AES256_GCM,data:QfukudwrnYFu6r7Lx9UOtGPqdkoGqke9ZNUjS6CqIwDgbU3ROT7HSC0+OVc8Fw==,iv:bi0fQAmUNldRO7P1sJMt8204lRsFALvv/xZBBpK0zUM=,tag:tAJ2ZqYbJKPOeWAKih63vg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N0Q3N1Z4bDR2QkxIMTho
            SG44bmg4aktLMG9KSTJqRm1QVG1FVGxlaEgwClhoZGhhYW5oNWtqRWxXWmo5UzdQ
            dk9mWnoyRFcyOHZIYWs0ZWJCQVdBRUUKLS0tIEhFdDNheW1YWEZYVWxlQ2NDSjBP
            UnQ4UVFVb2prekNDYXFEWnBYYXF0c2cKEwPDdn9X8zDvSUfNEGH2FLa2zm4gePeu
            mWWfjsM16lYCfdfIR6wB45xa7AEHKjLOKM7BXql4eUEa0Q37CZYFWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T06:33:23Z"
    mac: ENC[AES256_GCM,data:e9L4O6Ie6EGmpOToc+EE9Q+tdSXqw2oblbHxfOe6OEyl8mX2qTzqVvcRPuYw0jYldJuE8eziiagCFkQvskF/Y/+IBgIRrIrpQPovK/fvpU9Zkbx19t2OGgdnSXhf7VaA2ZVq3YGNkX4qpXgc9Gk7Yjls0D7rxIaXcKGi1NJO6Wc=,iv:NrgjTxkxgGADQj+sbYl6qSRilok5MszHhVnprhYiGu0=,tag:3E/H+8FUqn7wemsI6GruiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
