apiVersion: v1
kind: Secret
metadata:
    name: wil-auth-secret
    namespace: wil
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:3M+YZAqTBNh9oxSlwAe41IvhuV9U+D+xudSxmaFR13hg58vZJWAPAJYuYV7Usyt80cWuzhPwPZ4tf93OrbEJVA==,iv:yjeljsrtIBBmdblcN+6jjkm+u5Q26xa+UeWVq6mkUpo=,tag:UYQVYPUXw4WZw+9RsgWUhQ==,type:str]
    SITE_PASSWORD: ENC[AES256_GCM,data:xCbhveNB3Q==,iv:b3WpnGgYV+CGA2oPUhIHKw1DSTLmHcysNC4VKbx6hGM=,tag:EN+BspsZ+VkYyCYSHxj8zw==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUamxrVWpacXN0TUFGeFlk
            S3NFdHR6ZnY1TmhtaFE2MllCbGU5UklpVHlrCkxuSk1NaDlRUDdCOE9LVTRnSjZz
            TWZJOG5jdFp3TDhNV3l5ZU1id1VIdjAKLS0tIERuL2VQaHRPWENUTVJrM1NkKzRJ
            SjNCYmQ2TTBWVXdsQlNXcWhaOFFhbFUKQbKH3wD+CsqQa0emrSa9k92YWUhKtHLv
            p3RlYg2svsoiK7/8Dx01RuyLzppNOZxjEHDiDWFk5CIQpLiQyAunsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:46:24Z"
    mac: ENC[AES256_GCM,data:34KK+91+3OeCQafkUJgATbuununQVIUs+L2mQny118GCFkbSpkjn4lAcBjQMBZ/kbcxI7MIo2+GKYCMpzAjGtk47VTfee10tuZR6zeP+gibUuk3Em/w025J62e92YoJOdSnXNAlWaeEnevTv929CcUazdnDSz9mJMhI4yIMk+EI=,iv:zz968NRBjPdCZCMkSTUI0x4WjtTn8mSPM15VwXFLZBc=,tag:KJEomZobXByHHdikZPL7Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
