apiVersion: v1
kind: Secret
metadata:
    name: wil-auth-secret
    namespace: wil
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:5S3ZSSG8fIM9HpIDANrSLnmK7NW1iN2M+soaA7ms8xImaWgFzjutZxsZVirgr7WbrWVhs1ntgdHBNz4u+QWJgQ==,iv:AsFUvBa/LjK72fxrJZyVTP1XMD9jinCx8V7j2uoLNBE=,tag:Nse0KhhohlUjlxOWMzIFKA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:QbYeaAfLjquaayecHN1VfZ1ltOFHybKLBcjLn4HrVA==,iv:ROWH19z43VcanYW9UDYgQpNkPY0AJGo+5YwU/OId2Xg=,tag:l3fG6ewHrxYsHJnXteq8Sg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4THZBYVhLR3JuVmQxNzdn
            aTJmNWlDTytUMDJCMGNhK0NYWld2TzlwMUdNClNkM2FlSGkrdkNqd0pPd3ZnQ2E2
            OUVoenFQK1hncVRLUFZPaUxyVUhuZjAKLS0tIDZkTEJKWmNNcG1YcTFiTzBnclht
            Sy9qVDFUKzFGdEJLbTY3eW9pM0ErU0kK2PQBms8KkqUfyEk3XtwJKVh5+AsEhiIc
            fXqJeFKtRI7H7QQO9HUl3SEFWQdy875bZS0rZHfbbPtX3O5f5OM79g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T06:22:26Z"
    mac: ENC[AES256_GCM,data:jdCArfQn8gqM47VbrnVaEtL3Ihb/9jLeMzJTnsOxnFrjVyYYDGaQAWjTUiKEBBEKaF7cuHuVU9745hvETh3/HptcxLm1eGAqUaddBVGu+iEHwXngaFBHL7ivTNiL/YG9aC1+bnZtRAIUwO62oj4ZlgNCwih2c7aYvv4uF2+wT0o=,iv:IePlr4a+Qr2wHh0bY2KbyXkgGQuMuLdMgZ2kqW9VsIg=,tag:RqWpnYpeP68j6ZCPiICf5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
