apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: wil
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:kXDUnJM2S9Z6C9abHQ4PL7uqrsqBiDWYpQiGWJ2Aab8bGvjUOxHBBQ==,iv:88zJBQMREDVUMMP67P4JvB39F2gXE5vPea2YnKDx2Cw=,tag:LwBtmzOZ14fc0x3yxngHXA==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd05kWkxER0NmSU95OFUr
            NldrMGZkMEJ0NDY3R0hoOTY0b1NoWWRYMmlRCnRqVWNERlBwZDJrSmNJQ1hpQVBN
            R3VBcENnMXlmUVNzYk4veGt2c0dMSUkKLS0tIHpXbklyY0Y5QXNleWZZWVNVVHFF
            OG1iRjVsWEkwaFF2cVlVY3V3SW9wT00Kba3MlnwVxr3mM/fok6oo1XkMSlxiUzv+
            BQ4AOpWPhe9mhHza14iEUUlL8CYjb1Yxv6b2eXu8K1VjKrjEi3v9LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:29:06Z"
    mac: ENC[AES256_GCM,data:GEcstC2zaRoET7ab6nBVufb0Ch9IUYUPTy7Qd3b+5DBWsUU+23tKYqfKHEas01DrzFNP+l1Fd8OsP7gpkpkQduz55ltTejgk68xH+qtNNDfHnIDBdpb4GtBQN0Q90wUccLJ8s08fUJeRawjOruLslle9pwyWD2w4iuS2ACXQVf0=,iv:NW9L9WHlBAHhckHNzVFc3mHL5LBV1CrHkHrV+CgqexA=,tag:YtdYIekLhZAoC+ln6GjmHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
