apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: wil
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:kphMhWZGrIZ08Q==,iv:/v1DiiRENbKmuAXjg/QTQYsqHklxS+9nvYNgjiGbe6U=,tag:5iIwttXJdpt4BXjFAbAdFw==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZGpSdU43R2NkNnVuU01N
            T3FQQjBqc1lNK1JJMUM5dUlJVnBYSGFPd0JzCmFCbk80c0Y3azJucGJ2NnhiUUtV
            bTc2ZnNXWnVrOXFERFFuVjg5U0t5WWsKLS0tIFZMczNYdzJweitJQ0oxWkRKQ2p6
            eW1DdWgycEhncnpZckVwSWlNdCt1MWsKrxs9RxgcQFCBf2cZO75mBPgL8RsjjWIJ
            rdXL4/RT2Coscp702fbBHJGN/2SbOotBV8DCfUK+Un43IGvoxSyyAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T06:23:00Z"
    mac: ENC[AES256_GCM,data:b7IWQOKR1VXSLlyMSeALbDpSO5pIHo3pIkZmL7qEQFM72lCqOYPMa729wVsFvLBHocpcs3GoPlA4aOK4G+iIGH/EoEVz8nDBX7Nl8QvtJntd8HI6KfifOA0mMj8cCodJyZpPXPW9WTWxi4Tcb+p0ezI0CUmBHrY2h+6CkuuHjTo=,iv:YylCRE1Hdxv5rdbJoxpFRS7W3PwLk+DGHwvyRQbJKJo=,tag:+zelV77pyoDn6F6ssIYLvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
