apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: wil
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:U/Qc0qvF0sWZJhwA0PK83ee3hIkZL4cEZ/DkDrf8chSu5wvMPb/BC5onJkhl4vzz7eKkPiThN1w90w10Txu4EBMjuEpQ7eBhI6DgOTeNU7cxIGVrr63xcgnZ5kn/oTA6amSAcxi+vyklEsMBFPCBUEsWmR1hCR3U27wNsueCIHW+fl7Rmw==,iv:GmgbZtKxkD0irHRfdmcuFGN4lW5Jaj4Lr8U9cXhvAJs=,tag:Mx+31HGRxf6FN438x895+w==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VHY3OXNRYjMxNC9SRkho
            R0lZL2xQQk1lTUtBbUQ4RkpPSlQxMm5Id2s4CkZNSXFxQ3JGeWRuQXF1RVFjdXd5
            ZWlFN3UyMDBvbkRnd3V6RS9XNzdoQzAKLS0tIEc3bGdobkFSWjFhL3pEWlE1bmhw
            ZTNja0pSN3Nacm1ITzZwTDJWWDVzZ00K6zgAzz6KrJi8aShDZryBl7hpJdV/2mB0
            nFOj0kpYxKLtVzYr97IAhBTpooZSJPv2DIiuYQ+TZJrv0xlttmI5Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:29:18Z"
    mac: ENC[AES256_GCM,data:atcWr/AD8moiuF31oxK7p2SYRLCLazCWE9SB0mrTdMJkX70rvsPojil2ydLcgf3gIeMMDhlNkx+9evZJIFBoMoqUsRbGtgy5LA9SJVemodD+jwEkK50YW7eiHBBGw8q8HgBEaox3v7EEirrHT51FO6xEIcD5BMmv4aa9PGMqGKk=,iv:HcZJNERTYa0DThww8RY2chhhj9KZ3oGKRdYYbdKKziM=,tag:6QHc+oyLKTU2/p3UwBGVTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
