apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: wil
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ucToY8zj62GIhpDq3358irrQFeVG6/00pCr0abTdnoLmUaIvXHkAT5wkqA==,iv:LQNciTi9kbvKzj+HMw0nJM5oCyFJniBWX5JS0inOgqk=,tag:OEhjYbOgqepkQt48WyXgRg==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmNYbEE3MytwK0d6L1dx
            RzJaS0tpSTA0QWxCUVArUjFrc3pOdGEzcGhJCnRZak5zdFNMeVBKZnpnWVF4K2pY
            RXJZcHVvVWFEanBJZ1RvNXpEMURRbEkKLS0tIGJMSHZGOU1SeDdiekFyVEJMaXF4
            VlFTTnRLdFRyVDZoYmxiUThlTGlHY1kKYyj8+m+ZGaoa5kSW/v7R4tmJZbLqeU5y
            uBEhy5LJDbANstM+9v+qdOqMrlzPZ6TqlSh1bTQJsNTvBrmArXlvPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T06:23:00Z"
    mac: ENC[AES256_GCM,data:sK33FL8qnh+uIMmgJliejBm+4pdtKiZZZ2F1rIYZZuvZ0+KOx2oxzTgj2DwCqIrsLpJmSUAau/3PxOJDEgm0PIw9mr1KRkoeEbMTYIkfVVJE8FJmUpr4fvvFGk0meOP5zeAiuBoVgOR+/MkKfqzQ+A1LtzPKnKiLujvjVuCDFYA=,iv:No7gtzmTpZnxV7KuM8uKlLbNw5jTCGWRyAFd2IzKLZw=,tag:/ptjnM55wY2TZsDsWWYE3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
