apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: wil-binding
  namespace: wil
tunnelRef:
  kind: Tunnel
  name: wil-tunnel
subjects:
  - kind: Service
    name: wil
    spec:
      fqdn: wil.tapslab.com
      path: /
      protocol: http
