apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/tpural/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: metrics-server
  timeout: 2m
