apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7pRsmQKprnRDfbsMtErxpkcWqODnnX/JPEFDHMDgWrs=,iv:/WK6j57qkskgXTAsTOjClMLFr3p/n36G5Ek04Z0sPf0=,tag:ERHJqAtTFqTSPwmQoJCqQw==,type:str]
    N8N_DB_PASSWORD: ENC[AES256_GCM,data:Q3ObujQSZvU5R2LL3Hp2D6BflhPChH6zyFqFWgp5YoU=,iv:I+OwlrftC65DDc/1r6BQIj6ZRdOhkswYhZyZmS7OuAY=,tag:M0szhyDvrYZPGdNDPEC9bw==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdFRKcm9COENYRVQvQkNr
            T3VmQ2hDTlU3L2Z1T2tUZllnUEhrSGZTT25RCnJOSzBOZlZiUWhQdkMweWtaYVAv
            b2FCZy9UMkVGQSsycnRZdTlubWlyblkKLS0tIEd2S3JQSGtiQWZsYmJsZUFlTkg5
            ZmJUQjVuMC83TzFRUmZRMm5aQllRL1EKU5RtAbCj+GiNeTOgojvTILrP/Ak4QU2E
            c9U37REsO5tpgY9xfp346yLi564BwuV3xkyf8kYxH5YVOoMRGeYszg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T04:29:17Z"
    mac: ENC[AES256_GCM,data:1MoJazd7XGhLZpMwBj8fRtAizGcrCyXyMH5MdeLjhj4YOpv39m2RM4UyWHuYTw4WxgkfESZF3A+F1BHRbCtuNIsQcY9ZAByvXOE1Q+RkHNdI5UKiI82SUFUwl205zcuzdLc7Sm4z+S74X3UcUCKtpntCiBC3WTAb3MDWCToFcvk=,iv:Am97l24UYPOJpLRH9aj6j4GIw1h9Mxn1MsmmcNgJu8c=,tag:1i1EE5UYSRBwWdoinQjCzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
