apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
    external-dns.alpha.kubernetes.io/hostname: postgres.lan.tapslab.com
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: tcp-postgres
      protocol: TCP
      name: tcp-postgres
  selector:
    app: postgres
