apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/tpural/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/pihole
  prune: true
  sourceRef:
    kind: GitRepository
    name: pihole
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: pihole
      namespace: pihole
    - apiVersion: v1
      kind: Service
      name: pihole-lb
      namespace: pihole
