apiVersion: v1
kind: Service
metadata:
  name: pihole-headless
  namespace: pihole
  labels:
    app: pihole
spec:
  clusterIP: None
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
