# Install Gateway API CRDs first
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gateway-api
    namespace: flux-system
  path: ./config/crd/standard
  prune: true
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.1.0