apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/tpural/flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-assistant
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: home-assistant
      namespace: home-assistant
    - apiVersion: v1
      kind: Service
      name: home-assistant-lb
      namespace: home-assistant
