apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 5Gi
