apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: home-assistant
  labels:
    app: whisper
spec:
  type: ClusterIP
  selector:
    app: whisper
  ports:
  - name: wyoming
    port: 10300
    protocol: TCP
    targetPort: wyoming
