apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: openwebui
  namespace: openwebui
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames:
  - "openwebui.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: openwebui
      port: 80
