apiVersion: cloudflare-operator.io/v1
kind: Account
metadata:
  name: cloudflare-account
  namespace: cloudflare-operator
spec:
  apiToken:
    secretRef:
      name: cloudflare-api-token
      namespace: cloudflare-operator
