apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:APLxuihxuY3wAfus/NwTP1Ek/yqtddHfhhkOtbrU/u0nW+7VTO46pMQk7ylEU8+MI51R6VSw3do=,iv:vTm9AwKyB4xB076Hg1u/TrgE/8KNNKqFdU0ptcX1F6A=,tag:WuhArigMpk/dkUL7lfXoPQ==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:dvR7ZUSZiiqXN2TZSq+wD+RvS23jEDg90rGRATscAxb6BUa/7GlUU6Zb26FAFsIf7nJNaA==,iv:GNnut/lGVxPfGRhrnt6hgq4/tmbMzpFT4Oxq98NwHgI=,tag:an8zsV5J93hAXUPL9855Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pwl5ersszyeyx6hp53w72j4zhw3ucy8t37czcl2y9zlfcrjdqy5qs8cvxd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWWZRTllIVGZSdEJXWlFD
            Rk5ic3ZXU0EvR3hsVVhYNFlHUHJTZkNra3lZCmFPSzJMVzBGT3RBTUJQQVhaQzEv
            dmVNSHBtdXh0a3FzSmlqQ2pWWXNKcmMKLS0tIGhNWnYvRTdJS0NDT1p2a053MTY4
            QVJGS28zdmNmYi9kcVZiTDUzb1BFQVkK/90m45U5lSCw3WXlYeFGDjt35rDvY/FH
            5L8GjneMV2kRiMvDTI83e3HqJ6yMO9hEjrTAFpt+43ng+Bidj/crWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T22:07:36Z"
    mac: ENC[AES256_GCM,data:qkRaVtt2/2ZZZUVbvoBUJwX2oSDvyy/rMgtZHVRqX2LqA1MP6mAjj+USgQbjT6WjbplPXhvuqBWBxfXbZAyNOTMSUu8dQ+E2b32tysLdBkuu6D83QX49WrlHW/cYj/b4C3uPcTjnTLfNOpx3GHWrGEIVADxwmlc79/Uvb/zWFHk=,iv:iF5E+8E0zKrgWuQ0A/RasBnDwmfXl7yBjU8xD9gL3bM=,tag:4cKhpqYjZ16B4t4+HM3HDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
