apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  interval: 1h
  ref:
    tag: v0.13.1
  url: https://github.com/adyanth/cloudflare-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
    namespace: flux-system
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudflare-operator-crds
  interval: 10m
  path: ./apps/cloudflare-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
