apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: giraffe
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:EwBX4KKNht03sz5T4viOlN5ndgwbLOsoLT3kfv8MSlI7EWeTDv11jw==,iv:+5+pa7EyqAJT1/Odic2UBccKokaBahvmT5OAU+r2nGo=,tag:qn90j5aSC3ZgIXn0FgyV5A==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNSt3NThybER6TFhzWjRU
            R3E4ODZLeVJCeGovS29mQUFtOXNPRDNSemhvCjBkRGZDckVNb2Q1cWVTZno2UjZt
            bGlSOUFPY3k5MFVwOTdFRlBQUWlaVDAKLS0tIG1yMktERUh4OW1KMDlTK0RkU0Zu
            aWtXMStYUWlJWjlKQnAwNlBWUXZyMEEKJ3ImfWAnWywU6PodMJc9+jarbgPQST+6
            ZPedDXZumTmmVhwkUs+0XKpEtP0+xYKCqN8BCSJq0bO8nKTD6vO5aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T05:36:03Z"
    mac: ENC[AES256_GCM,data:FSG8+CxKMWT1J9KG5v1nVaN/QKj2its37hRkl9JII6h69QX521YrO5vNOBYJtS8E7ko55Q9juqYCi2vsA6fhV8iNSbc6ouB+G2LEgwlW5whx0IKajUmzd7YBBkGu4wq9LemkxMSrJywInoetY2CZ+NbwEpGqUxXBAJJMlaynaNQ=,iv:Ry5mGsRaGGvcMqM+d2WUWG2i6fom7hGb9R5iCPM9BCI=,tag:xPuxHqS6bOqat5DSK6xcYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
