apiVersion: apps/v1
kind: Deployment
metadata:
  name: giraffe
  namespace: giraffe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giraffe
  template:
    metadata:
      labels:
        app: giraffe
    spec:
      serviceAccountName: giraffe
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: giraffe
          image: ghcr.io/tpural/giraffe:0.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
