apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: giraffe
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:I6wI1FBY6Q28TXcAQ0bXkzBqT8dl/0LkWHoBu9Kvdany2SDDlWiCw2WQzrAoKJ2PeuCfv7DOtuvNXT242e9xvYyZHm25ALNkxqa3JPusi1cn4ExK90ZlhqpgQd8u2IJ2murQ8Rj7hZjjGDcYZObzhU1oGZg+bhQ8pwm/9u77RBlgSGAkTw==,iv:dl8HLXJDAjydeGxWa/3jBppy2SE+ASU/EIeB3g7HdcU=,tag:jwk3fdYS50EkeyNBEgYMHA==,type:str]
sops:
    age:
        - recipient: age1s6em2an08sfhsrrf8xjwclcykc8vu20dvp8xrw8ukzlg5dklq9wsxrqs69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTlZsa0Qyb2xhWWNqZEdv
            SG91K25rcmh0NkY5cHZ3bmF4UnVJWU9ndjI0Cmk0K2x0RDMxNnloYmJBYlMyWEFT
            VUZ4TE85VUUwYWxYMWtCdURSSkYxNGsKLS0tIDFPS054WFZqTDhpYmlHQVIvcTRL
            NHRzQlV4Y1MwaDd3S2VoVGtralNSWFkKJprf7UdVM0DSi6CgVaSE3Q9dt0qRC7JQ
            5hD903N7TshYz4O9tnFXkmndaemCNhcfWh9iBGOfQCXI3Rty6Ks5Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T05:36:03Z"
    mac: ENC[AES256_GCM,data:AJLYKVWwBE5AUTNjt5jSCRhgUDNIdbXHuxtmbcX1123V5dPNp+W7wx0ZiQEC+MFvZ2BdzXQdg9ezKofVxVdHHNxhrbHKCxPjQfRTsm+1SYKFMSmBUERZICA0MsrD3k1QyXgTFNMhdeIKdMpCw7sD4hIRwmF0Cr+pPIHabHUAh4c=,iv:GGnL14O03pYXoaUz3SV6nlMttwP+y83ivLWa98YhAuQ=,tag:Xe7OkDi49HYdHghI2k6PAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
