apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-data-pvc
  namespace: portfolio-site
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-retain



